WIP:allow for modifiying sort parameters in user interface
hipster-philology/pyrrha pull request #189
Opened 2020-07-27 07:13 UTC by carinedengler

I opened a WIP pull request with what I have done so far (in 0.5 days), I have not yet focused on adding tests or generalizing the solution,

* is this how you imagined that the solution should be integrated into the user interface?
* if yes, I have not found other radio buttons / checkboxes in the application, what kind of design would you like for them?

2020-07-28 09:00 UTC, PonteIneptique commented on app/templates/main/tokens_search_through_fields.html
> +                        <input id="orderByForm" type="radio" name="orderBy" value="form">
I think I'd probably go with two plain `<a>` links rather than an input, one arrow toward top, one towards bottom, with a simple filter.

2020-07-29 08:42 UTC, PonteIneptique commented
The only thing remaining is to pass the search parameters through, which would mean passing them from the back end to the front end and reusing them in the link as kwargs probably.

2020-07-29 10:16 UTC, carinedengler commented
I was wondering if you would like me to add some tests as well - I now worked for 1d in total on this issue

2020-10-01 08:09 UTC, MrGecko requested changes
I'm not sure to understand the use of ```search_kwargs```, which I suppose should keep the current search parameters when building the sort links.
It looks like the ```corpus_id``` is passed but the form,lemma,pos,morph inputs are not. Thus the sort only sorts an empty search.

2020-10-01 08:46 UTC, carinedengler commented
silly oversight, I corrected it

2020-10-01 11:23 UTC, MrGecko commented
I think we need a custom collation function to support both case insensitive sorts and utf8:

I'd create the collation first in ```app/__init__.py```:
```python
def nocase_utf8_strcmp(x,y):
    return 1 if x.lower() > y.lower() else -1 if x.lower() < y.lower() else 0

@event.listens_for(Engine, "connect")
def create_unicode_nocase_collation(dbapi_connection, connection_record):
    cursor = dbapi_connection.cursor()
    dbapi_connection.create_collation('unicode_nocase', nocase_utf8_strcmp)
    cursor.close()
```
then use the collate function inside the ```order_by``` clause :
```python
tokens = WordToken.query.filter(*args).order_by(
        asc(collate(WordToken.form, 'unicode_nocase')  #hard coded asc order for illustration purpose
)
```

2020-10-01 15:01 UTC, carinedengler commented
I'd use the solution with `func.lower` I just committed, do you see any inconveniences in it?

2020-10-01 15:16 UTC, MrGecko commented
Does not work as expected on my side 
![image](https://user-images.githubusercontent.com/65418/94828067-658eb480-0409-11eb-9cfe-2d03c303f455.png)

**NB:** forgot to mention that the sort buttons are inverted. The arrow down must sort alphabetically. Also I think it would be clearer if they were present in the result table, since they sort the result and not the parameters themselves.

2020-10-01 15:37 UTC, carinedengler commented
weird, I get this

![sort-order-lower](https://user-images.githubusercontent.com/56160522/94831108-9ae8d180-040c-11eb-8ec6-aa1d3f78ae98.png)

I'll look into it again with a different set of data and I'll fix the buttons

2020-10-02 11:49 UTC, carinedengler commented
I double-checked it with a different set of data

![control-list-sort](https://user-images.githubusercontent.com/56160522/94920112-ec996680-04b5-11eb-97c5-15e59634332d.png)

I fixed the inverted buttons

2020-10-02 11:52 UTC, PonteIneptique commented
Could it be a version of SQLAlchemy / FlaskSQLAlchemy / SQLite kind of issue between you two ?

2020-10-02 11:55 UTC, carinedengler commented
```
python --version
Python 3.7.3

sqlite3 --version
3.27.2 2019-02-25 16:06:06 bd49a8271d650fa89e446b42e513b595a717b9212c91dd384aab871fc1d0alt1

pip list
Package            Version
------------------ -------
attrs              19.3.0
blinker            1.4
click              7.1.1
cov-core           1.15.0
coverage           5.2
Flask              1.1.2
Flask-Compress     1.4.0
Flask-Login        0.5.0
Flask-Mail         0.9.1
Flask-Markdown     0.3
Flask-SQLAlchemy   2.4.1
Flask-Testing      0.8.0
Flask-WTF          0.14.3
importlib-metadata 1.7.0
itsdangerous       1.1.0
Jinja2             2.11.2
Markdown           3.2.2
MarkupSafe         1.1.1
mock               4.0.2
more-itertools     8.4.0
nose               1.3.7
packaging          20.4
pbr                4.0.3
pip                20.1.1
pkg-resources      0.0.0
pluggy             0.13.1
py                 1.9.0
pyparsing          2.4.7
pytest             5.4.3
python-slugify     4.0.0
PyYAML             3.13
redis              2.10.6
rq                 0.10.0
selenium           3.141.0
setuptools         49.2.0
six                1.14.0
SQLAlchemy         1.3.18
text-unidecode     1.3
Unidecode          1.1.1
urllib3            1.25.9
wcwidth            0.2.5
Werkzeug           0.15.3
wheel              0.34.2
WTForms            2.2.1
zipp               3.1.0
```

2020-10-02 15:10 UTC, carinedengler commented
fixed an error introduced by `func.lower` and moved asc/desc sorting to results table

2020-10-05 13:18 UTC, MrGecko approved these changes
Thank you @carinedengler , I think this last commit fixed the issue.

2020-10-05 13:18 UTC, merged