WIP:switch control lists
hipster-philology/pyrrha pull request #191
Opened 2020-07-29 14:13 UTC by carinedengler

Does this solution with a separate view and the drop-down menu for switching control lists meet your expectations? I passed about two thirds of a day on this ticket so far. I intend to add some tests as soon as you confirm me the proposed solution.

2020-07-29 14:19 UTC, PonteIneptique submitted a review, later dismissed
Great. As for tests, the École is actually closed, I am just really bad at not working during my vacations. Vincent Jolivet is the budget decider, I am just the original coder / manager of this repository :)

2020-07-29 14:19 UTC, PonteIneptique commented on app/main/views/corpus.py
> +def _get_available():
I like this.

2020-07-29 14:19 UTC, PonteIneptique commented on app/templates/macros/nav_macros.html
> +  <li class="nav-item"><a class="nav-link" href="{{url_for("main.control_list_switch", corpus_id=corpus.id)}}">
I think the way it is right now the link would be viewable by *not owners* which should be avoided.

2020-07-29 14:19 UTC, PonteIneptique commented on app/templates/main/control_list_switch.html
> +{% block content %}
I think you are missing the `<form>`

2020-07-29 14:35 UTC, carinedengler commented
> Great. As for tests, the École is actually closed, I am just really bad at not working during my vacations. 

I noticed, I started to feel really bad when pushing something :-) I actually didn't expect any replies before the 24th, so please don't feel obliged to comment on my work until then.

2020-07-29 14:36 UTC, PonteIneptique commented
I am really bad when it comes to one of my baby software :)

2020-07-30 11:00 UTC, PonteIneptique commented
I saw that the code does not check if the user is the owner of the Corpus before switching the control list :) I don't know where to put it in the review.

2020-08-25 15:32 UTC, MrGecko commented on app/templates/macros/nav_macros.html
> +  <li class="nav-item"><a class="nav-link" href="{{url_for("main.control_list_switch", corpus_id=corpus.id)}}">
The view itself should not be accessible either.

2020-08-25 15:34 UTC, MrGecko requested changes
Need to prevent _non owners or admins_  to 
1) view the new link
2) access the new view

2020-08-27 07:04 UTC, carinedengler commented
> Need to prevent _non owners or admins_ to

just to confirm, do you mean that _non admins_ should not be able to view the link/the new view or that _admins_ should not be able to view it?

2020-08-27 07:09 UTC, PonteIneptique commented
I dive in: I think website admin should be able to see it. The view and link should be visible to admin AND owners.

2020-08-27 07:20 UTC, carinedengler commented
I pushed an update to make the link/view only accessible to admins/owners of the corpus

2020-08-27 11:58 UTC, carinedengler commented
sorry, I didn't notice that the changes had not been included, they have been now

2020-08-27 13:49 UTC, PonteIneptique commented
Looking at the proposal, I think this ties also with the issue in #202 , if users connected to this corpus are switched, they won't be switch to the new control list.

2020-08-31 08:54 UTC, carinedengler commented
I will look into it

2020-10-05 13:07 UTC, MrGecko commented
The #202 has been merged, you should be able to resume your work on this issue

2020-10-06 10:16 UTC, carinedengler commented
I integrated managing access to the new/old control lists for all users (it turned out that I couldn't use @FrFerry function for it since it is implicitely for the same control list)

2020-10-22 07:48 UTC, MrGecko commented
@PonteIneptique should admin/or private list owners be able to switch a corpus to a private list (if they have the right to access it), or should users only be able to switch to public lists?

2020-10-22 07:50 UTC, PonteIneptique commented
You should be able to switch to a private list.

Le jeu. 22 oct. 2020 à 9:48 AM, Julien Pilla <notifications@github.com> a
écrit :

> @PonteIneptique <https://github.com/PonteIneptique> should admin/or
> private list owners be able to switch a corpus to a private list (if they
> have the right to access it), or should users only be able to switch to
> public lists?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hipster-philology/pyrrha/pull/191#issuecomment-714302256>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOXEZUUBEWXKYNLVR7HGGDSL7PUPANCNFSM4PLUROGQ>
> .
>

2020-10-22 08:14 UTC, MrGecko commented
> You should be able to switch to a private list.

Then i'm not sure I understand the following warning note:
https://github.com/hipster-philology/pyrrha/blob/e9ff1fda394e588654021652154a776322a875c5/app/models/control_lists.py#L114-L120

Indeed ```ControlLists.get_available``` can fetch private lists, but only if you are a member of this list: being an admin does not grant you the right to switch to a control list if you are not explicitly part of it.

2020-10-22 08:33 UTC, PonteIneptique commented
Sorry. I'll reformulate. You should be as owner able to switch to private
list. Admin should not.

Le jeu. 22 oct. 2020 à 10:15 AM, Julien Pilla <notifications@github.com> a
écrit :

> You should be able to switch to a private list.
>
> Then i'm not sure I understand the following warning note:
>
> https://github.com/hipster-philology/pyrrha/blob/e9ff1fda394e588654021652154a776322a875c5/app/models/control_lists.py#L114-L120
>
> Indeed ControlLists.get_available can fetch private lists, but only if
> you are a member of this list: being an admin does not grant you the right
> to switch to a control list if you are not explicitly part of it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hipster-philology/pyrrha/pull/191#issuecomment-714317482>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOXEZRYUIFBTZ7NQQCPGU3SL7SZDANCNFSM4PLUROGQ>
> .
>

2020-10-22 09:50 UTC, MrGecko commented
Looks good to me then!

@carinedengler I think it woud be nice if the name of the corpus was printed above the form; even better if the current control list was preselected (or just printed next to the corpus name).

2020-10-26 09:14 UTC, carinedengler commented
> Looks good to me then!
> 
> @carinedengler I think it woud be nice if the name of the corpus was printed above the form; even better if the current control list was preselected (or just printed next to the corpus name).

I added a line with the current control list name and the current control list is now preselected

2020-10-26 14:55 UTC, MrGecko approved these changes

2020-10-26 14:57 UTC, merged