Give read access to control lists when giving access to corpora.
hipster-philology/pyrrha pull request #202
Opened 2020-08-21 13:10 UTC by FrFerry

closes #182

2020-08-24 09:15 UTC, FrFerry commented
> Hey @FrFerry :)
> Thank you for this PR. Are you working with @carinedengler ?

Hello @PonteIneptique, yes I'm working with her at Logilab :)

2020-08-24 09:18 UTC, PonteIneptique commented
Hi !
Good (or sad), I did not know if we had a new foreign to the project enthusiast :)

2020-08-25 14:46 UTC, MrGecko approved these changes

2020-09-07 09:22 UTC, PonteIneptique commented
If you extract the function, the kwargs parameters should be : `_commit=True`

2020-09-08 07:29 UTC, PonteIneptique commented on app/main/views/dashboard.py
> +def update_control_list_user(corpus, clu_list, users, _commit=True):
Hey, to go back to typing, typically, this line should look like the following:

```python
from typing import List
# Also Import Corpus, ControlList and User but I think it's already done
def update_control_list_user(corpus: Corpus, clu_list: List[ControlList], users: List[User], _commit: bool = True):
    """ And the comment about what it does
    """
```

2020-09-08 07:29 UTC, PonteIneptique commented on app/main/views/dashboard.py
> +def update_control_list_user(corpus, clu_list, users, _commit=True):
Otherwise, I wonder if it should be in the route file or in a method actually, not sure. I'll let @MrGecko comment on this.

2020-09-30 08:53 UTC, MrGecko requested changes
https://github.com/hipster-philology/pyrrha/blob/298514ea3827fdd07624c9c0ce2baf50bec575f7/app/main/views/dashboard.py#L95-L98
Since the flag is set to False for all users, the existing ownership is lost in the process

2020-10-02 09:21 UTC, FrFerry commented
> https://github.com/hipster-philology/pyrrha/blob/298514ea3827fdd07624c9c0ce2baf50bec575f7/app/main/views/dashboard.py#L95-L98
> 
> Since the flag is set to False for all users, the existing ownership is lost in the process

Yes, indeed. I added a list to record all control list owner user id to be sure to keep them.

(However, I had some trouble with git ... I hope it's not an issue :( )

2020-10-05 13:04 UTC, MrGecko approved these changes
No problem ;)
Thanks for the fix

2020-10-05 13:04 UTC, merged