WIP: add option to hide columns (closes #222)
hipster-philology/pyrrha pull request #224
Opened 2020-10-13 14:14 UTC by carinedengler

hi,

I added the option to hide columns (its on top of the branch with the preferences view),

* added hiding columns to preferences
* added hiding columns to corpus creation
* do not display columns which have been marked as hidden

However, I'm not sure how to add the 'unhide' feature in the table views, would you like a button 'show hidden columns'? Or being able to show/hide individual columns?

(Also, I'm not particularly fond of my adaptation of the migration functionality, but I wanted to confirm with you first that this is the way to do it before I'm cleaning it up).

2020-10-13 14:25 UTC, PonteIneptique requested changes

2020-10-13 14:29 UTC, carinedengler commented on app/main/views/corpus.py
> +def _update_columns(corpus: Corpus):
> Same comment as per #221 : it would be nicer as a method of Corpus.

I will definitely change this in both branches, I just added it here at the same place because I'm waiting for @MrGecko to pass by #221 so that I can integrate all changes at more or less the same time

2020-10-28 09:26 UTC, carinedengler commented
We were wondering if this solution would be acceptable to you? In this case, we could include the option to hide the column containing the number of similar tokens in this as well?

2020-10-28 10:28 UTC, PonteIneptique commented
If it works, it is acceptable. I really think the migration system is awful, it's a hack we had to do... So I would not worry about it...

2020-11-02 14:19 UTC, carinedengler commented
Hi,
I integrated the requested changes and also hid the search fields for hidden columns. I think my earlier question has been lost in the commentries

>     However, I'm not sure how to add the 'unhide' feature in the table views, would you like a button 'show hidden columns'? Or being able to show/hide individual columns?

What solution would you prefer? Or should the users not be able to unhide the columns without adapting the preferences?

2020-11-03 08:14 UTC, PonteIneptique commented
Looking at it this morning.

2020-11-03 08:28 UTC, PonteIneptique commented
So to reply, I think unhide should stay in the current Preference view. I would not add it to the table.

2020-11-03 08:32 UTC, PonteIneptique commented
There is one impact I did not foresee, which is get_similar_batch which will need to be updated according to the columns shown : https://github.com/carinedengler/pyrrha/blob/222/app/models/corpus.py#L694-L708

2020-11-03 08:32 UTC, PonteIneptique commented
But I think it's for another PR if I remember well.

2020-11-04 09:43 UTC, carinedengler commented
> But I think it's for another PR if I remember well.

yes, I opened the related issue #229

2020-11-04 09:44 UTC, carinedengler commented
should we add hiding the 'Similar' column in this merge request as well? or would you like to have it in a separate issue?

2020-11-04 09:46 UTC, carinedengler commented
I will look into the failed checks right away

2020-11-04 10:44 UTC, PonteIneptique commented
> should we add hiding the 'Similar' column in this merge request as well? or would you like to have it in a separate issue?

I think this might be the best place to do it :)

2020-11-09 14:52 UTC, MrGecko commented
Hello @carinedengler, everything looks good to me so far; could you please add the Similar column too?

2020-11-09 14:57 UTC, carinedengler commented
> Hello @carinedengler, everything looks good to me so far; could you please add the Similar column too?

I will try to do so (and to fix the pipeline) as soon as possible - I am a little tied up with my other responsibilities right now, but I will try to work on it tomorrow

2020-11-10 10:52 UTC, carinedengler commented
I fixed the tests and added the 'Similar' column to the columns that can be hidden

2020-11-10 12:09 UTC, PonteIneptique commented
Can you make it so that the correct token in particular makes use of this, by not retrieving unnecessary information  ? Most importantly the similar but if you can do the same for morph, pos and lemma, that would be neat.

https://github.com/hipster-philology/pyrrha/blob/2ddea3345d2e299f2e008dfcba1076bb4d83db81/app/main/views/tokens.py#L21-L40

2020-11-16 13:40 UTC, carinedengler commented
> Can you make it so that the correct token in particular makes use of this, by not retrieving unnecessary information ? Most importantly the similar but if you can do the same for morph, pos and lemma, that would be neat.

wouldn't that be part of #229? I would like @FrFerry to take over for this ticket if that's o.k. for you?

2020-11-16 13:41 UTC, carinedengler commented
there's still a test that's not passing, I will fix it (the 3 others do not pass on dev either)

2020-11-16 13:42 UTC, PonteIneptique commented
Yes for sure, the splitting of the ticket here is still strange to me but I understand,

2020-11-16 14:29 UTC, carinedengler commented
> there's still a test that's not passing, I will fix it (the 3 others do not pass on dev either)

fixed it

2020-11-27 09:37 UTC, MrGecko approved these changes

2020-11-27 09:38 UTC, merged