Issue223
hipster-philology/pyrrha pull request #226
Opened 2020-10-28 13:58 UTC by FrFerry

close: https://github.com/hipster-philology/pyrrha/issues/223

* add a method to `app.models.corpus.Corpus` to change `left_context` and `right_context`, then update all `WordToken` according to these new contexts;
* add a method to `app.models.corpus.WordToken` to update left and right contexts ;
* add in db `left_context` and `right_context` when we create a new `Corpus`, it looks like these values wasn't saved in db. Maybe it hadn't be detected because we use them only at Corpus creation (or maybe I'm wrong) ;
* add options to modify left and right context in Corpus preference view.

François.

2020-10-28 16:17 UTC, PonteIneptique requested changes
The interface and the HTML are alright, but the implementation of the massive update can't stay that way for performance reason. This is something we know only because we fixed this back in the old days for the insert.

Given the effect of this function, I'd like to have a simple unit test for this feature.

2020-10-28 16:17 UTC, PonteIneptique commented on app/models/corpus.py
> +    def rebuild_context(
This is a very expensive way to do this and needs to be rewritten. Updating each tokens by getting all text will be too hard.

Cf. https://github.com/hipster-philology/pyrrha/blob/deb25895d768aa04ec5b87e0202fe933fcdb3921/app/models/corpus.py#L816-L897

Basically, have a Static method update_batch_context(corpus_id, left_context, right_context)
1. You should retrieve all tokens text, using order_id. This will allow for iteration and retrieve each token only once. You don't need the annotations, only `form`, `order_id` and primary key which is `id`.
2. Prepare an [bulk_update_mappings](https://docs.sqlalchemy.org/en/13/orm/session_api.html#sqlalchemy.orm.session.Session.bulk_update_mappings)
3. Commit if _commit is True

2020-10-28 16:17 UTC, PonteIneptique commented on app/models/corpus.py
> +                f"cannot set context to 'left: {context_left}, right: {context_right}'"
Can you capitalize cannot ?

2020-10-29 18:26 UTC, PonteIneptique requested changes
Merci beaucoup, cela devrait améliorer les performances. Encore deux toutes petites remarques si possible :)

2020-10-29 18:26 UTC, PonteIneptique commented on tests/test_models/test_word_token.py
> +        self.assertEqual(len(right_context), 4)
Can you add a test here to check that the context is the right one, not only in term of size ? :)

2020-10-29 18:26 UTC, PonteIneptique commented on app/models/corpus.py
> +        tokens = WordToken.query.filter_by(corpus=corpus_id).order_by(WordToken.order_id).all()
It's much better, thank you.
Could you still remove some data retrieved, ie by loading only the necessary columns (order_id, id, form) ? https://stackoverflow.com/questions/11530196/flask-sqlalchemy-query-specify-column-names

2020-10-30 07:55 UTC, PonteIneptique approved these changes
Looks good to me. Merci pour la réactivité.
À ton tour @MrGecko

2020-11-09 11:11 UTC, MrGecko commented
Thanks for the work @FrFerry ! I'd suggest clamping the context to reasonable size values, like 0-10 or It'd be possible to clog the db with larges values. @PonteIneptique ?

2020-11-09 12:35 UTC, PonteIneptique commented
Good point, I'd make it another issue and use a generic constant like MAX PAGE SIZE or the configuration constants. And apply it to corpus creation. What do you think ?

2020-11-09 14:55 UTC, MrGecko commented
> Good point, I'd make it another issue and use a generic constant like MAX PAGE SIZE or the configuration constants. And apply it to corpus creation. What do you think ?

We should indeed apply the same range limitation in the corpus creation and somehow define it as a configuration constant :+1:

2020-11-09 14:55 UTC, MrGecko submitted a review, later dismissed

2020-11-27 10:23 UTC, MrGecko approved these changes

2020-11-30 10:34 UTC, merged

2020-11-30 10:37 UTC, MrGecko commented
fixed the merge issue in views/corpus.py