Pyrrha Localization : Language bo_CN
hipster-philology/pyrrha pull request #284
Opened 2022-05-05 18:09 UTC by Lungsang-bod

2022-05-05 18:53 UTC, PonteIneptique requested changes
I spotted many non translated things. Is it intentional ?

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_del_row.html
> +    <h1>{{ _('Corpus') }} {{corpus.name}} - Remove a token</h1>
Shouldn't `Remove a token` be translated too ?

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_del_row.html
>      <p>This page allows you to remove the following one</p>
Missing translation

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_edit_form.html
> +    <h1>{{ _('Corpus') }} {{corpus.name}} - Token Edit</h1>
Missing translation for `Token Edit`

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_edit_form.html
>      <p>This page allows you to correct the form of the following token</p>
Missing translation for whole paragraph

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_edit_history.html
> +<h1>{{ _('Corpus') }} {{corpus.name}} - History of tokens edition</h1>
Missing translation for `History of tokens edition`

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_export.html
> +<h1>{{ _('Corpus') }} {{corpus.name}} - Download </h1>
Missing translation for `Download`

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_history.html
> +<h1>{{ _('Corpus') }} {{corpus.name}} - List of tokens </h1>
Missing translation for `List of tokens`

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_search_through_fields.html
> +    <h1 class="mt-3"><i class="fa fa-search mr-2"></i>{{ _('Corpus') }} {{ corpus.name }} - Search tokens within the corpus </h1>
Missing translation for `Search tokens within the corpus`

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_similar_to_record.html
> +<h1>{{ _('Corpus') }} {{corpus.name}} - List of tokens </h1>
Missing translation for `List of tokens`

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/main/tokens_similar_to_token.html
> +<h1>{{ _('Corpus') }} {{corpus.name}} - Similar tokens </h1>
Missing translation for `Similar tokens`

2022-05-05 18:53 UTC, PonteIneptique commented on app/templates/macros/nav_macros.html
>                  Annotations
Missing translation for `Annotations`

2022-05-06 04:53 UTC, Lungsang-bod commented
> I spotted many non translated things. Is it intentional ?

Yes @PonteIneptique , there are still lots of non translated things because right now I dont have the exact translation word for them.   But if it's okay, i can mark and extract all the remaining translatable strings in message.po

2022-05-06 05:25 UTC, PonteIneptique commented
> > I spotted many non translated things. Is it intentional ?
> 
> Yes @PonteIneptique , there are still lots of non translated things because right now I dont have the exact translation word for them. But if it's okay, i can mark and extract all the remaining translatable strings in message.po :)

Yup, I think it would be good to at least have everything in extracted, even if the translation is incomplete. This will allow for only working on `message.po` in the future :)

2022-05-06 06:23 UTC, Lungsang-bod commented
> > > I spotted many non translated things. Is it intentional ?
> > 
> > 
> > Yes @PonteIneptique , there are still lots of non translated things because right now I dont have the exact translation word for them. But if it's okay, i can mark and extract all the remaining translatable strings in message.po :)
> 
> Yup, I think it would be good to at least have everything in extracted, even if the translation is incomplete. This will allow for only working on `message.po` in the future :)

Okay ! i am on it :)

2022-05-11 04:16 UTC, Lungsang-bod commented on app/templates/main/corpus_info.html
> +                        {{ _('lemma were correct from lemmatization. It means you corrected') }} {{stats.lemma_count}} {{ _('lemma.') }}
Okay :) i will try this one. thank you !

2022-05-12 18:47 UTC, Lungsang-bod commented on app/templates/main/corpus_info.html
> +                        {{ _('lemma were correct from lemmatization. It means you corrected') }} {{stats.lemma_count}} {{ _('lemma.') }}
I think above two methods are used for extracting from python source code. Not from template. I tried them in template and it's not extracting :)

2022-05-12 18:52 UTC, PonteIneptique commented on app/templates/main/corpus_info.html
> +                        {{ _('lemma were correct from lemmatization. It means you corrected') }} {{stats.lemma_count}} {{ _('lemma.') }}
Hmm, I'll have a look at the end of the PR for this kinda things, I also want to add a user pref :)

2022-05-12 18:58 UTC, Lungsang-bod commented on app/templates/main/corpus_info.html
> +                        {{ _('lemma were correct from lemmatization. It means you corrected') }} {{stats.lemma_count}} {{ _('lemma.') }}
```<p>{{ _('Alternatively, you can paste the following link in your browser's address bar:') }}</p>```
When extracting this sentence, the browser's (') is causing a problem.

```<p>The {{ config.APP_NAME }} Team</p>```

```<p>To reset your password, <a href="{{ reset_link }}">click here</a>.</p>```

There are many sentences like above three and I am figuring out how to extract the whole sentence without to break them up. Please let me know if you have any solution :)

2022-05-12 19:06 UTC, Lungsang-bod commented on app/templates/main/corpus_info.html
> +                        {{ _('lemma were correct from lemmatization. It means you corrected') }} {{stats.lemma_count}} {{ _('lemma.') }}
```annotations <br />corrected```
Including these kind, where </br> is put between a sentence.

2022-05-12 19:51 UTC, Lungsang-bod commented on app/templates/main/corpus_info.html
> +                        {{ _('lemma were correct from lemmatization. It means you corrected') }} {{stats.lemma_count}} {{ _('lemma.') }}
> Hmm, I'll have a look at the end of the PR for this kinda things, I also want to add a user pref :)

Okay :)

2022-06-29 13:15 UTC, PonteIneptique commented
Hey @Lungsang-bod , I was actually waiting for your "go" :)
I don't know if I'll have the time to review and correct by next week, but I'll try :)

2022-06-29 19:29 UTC, Lungsang-bod commented
Thank you @PonteIneptique :)

2022-07-05 12:47 UTC, Lungsang-bod commented
Sure @PonteIneptique, in the meantime we will push the translated strings in the PR. Please have a look when time permits you. 
Wishing the best for your new work :)

2022-07-26 16:23 UTC, PonteIneptique commented
I'll try to deal with this tomorrow, if I can. By the way, have you and your team published any paper I could see about what you do with Pyrrha ? :)

2022-07-27 09:19 UTC, merged

2022-07-27 09:46 UTC, PonteIneptique commented
@Lungsang-bod I reworked your PR in https://github.com/hipster-philology/pyrrha/pull/285 so that it includes the necessary bits.

Can you check that it works for you ?

By the way, if you need a variable in a template, you can use the following snippet:

```html
{{_("lemma were correct from lemmatization. It means you corrected %(count)s lemma.", count=stats.lemma_count)}}
```

https://github.com/hipster-philology/pyrrha/blob/0f6b01f4ee171affb3f20f01691bb54fead943d1/app/templates/main/corpus_info.html#L57

For future message upgrades, please check the readme.md but basically run 

```sh
python manage.py translate update
# Change the translation and then do
python manage.py translate compile
```

and please commit with prefix `(i18n/bo_CN) and then your message`

Finally, you might need to run

```sh
python manage.py db-upgrade user-language
```

as I modified the models :)

2022-08-05 05:37 UTC, Lungsang-bod commented
> I'll try to deal with this tomorrow, if I can. By the way, have you and your team published any paper I could see about what you do with Pyrrha ? :)

I will ask my team if any paper is published regarding Pyrrha and will let you know :)