Création tests account different cases
hipster-philology/pyrrha pull request #308
Opened 2024-03-11 15:41 UTC by Juliettejns

- création d'un test qui vérifie qu'un même compte est créé indépendant de la case de l'email employé
- création d'un test qui vérifie que l'on peut se log sur un compte qu'importe la case de l'email.

2024-03-11 15:45 UTC, PonteIneptique requested changes
Please correct the test according to my feedback, and change the error message for the email in the application :)

2024-03-11 15:45 UTC, PonteIneptique commented on tests/test_selenium/test_user_account.py
> +        user = User.query.filter(
It should check there is only one result, and not that one exists :)

2024-03-11 15:45 UTC, PonteIneptique commented on tests/test_selenium/test_user_account.py
> +            sorted(['Email already registered. (Did you mean to log in instead?)']),
Maybe change the error message in the app for this one. `Unable to register a user with the provided information. Link to password reset`

2024-03-11 15:45 UTC, PonteIneptique commented on tests/test_selenium/test_user_account.py
> +    def test_connexion_with_different_cases(self):
Perfect

2024-03-12 09:19 UTC, Juliettejns commented
Done!

2024-03-12 11:06 UTC, merged