Case sensitive
hipster-philology/pyrrha pull request #309
Opened 2024-03-13 15:33 UTC by Juliettejns

- Ajout de la possibilité de rechercher dans les tokens d'un corpus avec ou sans case sensitivity. (au niveau de l'app)
- Modification du test raté à cause de la case sensitivity en fonction de ça.

Screen de l'app après cette modification:
![image](https://github.com/hipster-philology/pyrrha/assets/56683417/993a50fd-d238-42a0-9e83-308f54063aed)

2024-03-13 18:36 UTC, PonteIneptique requested changes

2024-03-13 18:36 UTC, PonteIneptique commented on app/main/views/tokens.py
> +    caseIssensitive=True
`caseInsensitive` would be better I think (typo in the variable name ?

2024-03-13 18:36 UTC, PonteIneptique commented on app/utils/forms.py
> +            elif case:
You are missing a "notIlike" no ?

2024-03-13 18:36 UTC, PonteIneptique commented on app/utils/forms.py
> +def column_search_filter(field, value: str, case=True) -> list:
I would rename case to case_sensitive to be clearer...

2024-03-13 18:36 UTC, PonteIneptique commented on tests/test_selenium/base.py
> +        print(case)
Remove ?

2024-03-13 18:36 UTC, PonteIneptique commented on tests/test_selenium/test_tokens_search_through_fields.py
>      def test_search_with_or_operator(self):
you should probably add a new test that search with case insensitive (or the other, not clear to me what's going on here).

2024-03-13 18:36 UTC, PonteIneptique commented on app/main/views/tokens.py
> +    # test suppression:
I think more and more the search function within the search route should be externalized, it would be easier to test as well. Basically a search function that text the form input. But that's for later ;)

2024-03-14 08:27 UTC, Juliettejns commented on tests/test_selenium/test_tokens_search_through_fields.py
>      def test_search_with_or_operator(self):
It's already done on line 160 with 'Seinz' in capital letters and on line 161 with 'sein*' in lowercase. It compares the results for the search 'seint|seinz|Seinz|seinte' and the result for 'sein*'. Previously, they were not the same before adding case insensitivity, as 'Seinz' was not taken into account for the 'sein*' search, causing the test to fail. I added case insensitivity on line 161, and now the test is no longer failing. Should I create another test specifically for case sensitivity nonetheless?

2024-03-14 08:37 UTC, PonteIneptique commented on tests/test_selenium/test_tokens_search_through_fields.py
>      def test_search_with_or_operator(self):
Yes :)

2024-03-14 12:10 UTC, merged